### ISSUE TITLE
Compatibility Issues

### ISSUE THREAD

**Issue by duodenum96** [MattWillFlood/EntropyHub.jl#3]
Hello,

Is this package still maintained? I'm having these compatibility issues:

`Unsatisfiable requirements detected for package FourierAnalysis [e7e9c730]:
 FourierAnalysis [e7e9c730] log:
 ├─possible versions are: 1.0.0-1.2.1 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 1.0.0-1.2.1
 ├─restricted by compatibility requirements with DSP [717857b8] to versions: 1.0.0-1.1.2 or uninstalled, leaving only versions: 1.0.0-1.1.2
 │ └─DSP [717857b8] log:
 │   ├─possible versions are: 0.5.1-0.7.5 or uninstalled
 │   ├─restricted to versions * by an explicit requirement, leaving only versions 0.5.1-0.7.5
 │   └─restricted by compatibility requirements with EntropyHub [3938faea] to versions: 0.6.8-0.6.10
 │     └─EntropyHub [3938faea] log:
 │       ├─possible versions are: 0.1.0-0.2.0 or uninstalled
 │       └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.2.0
 └─restricted by compatibility requirements with RecipesBase [3cdcf5f2] to versions: 1.2.0-1.2.1 or uninstalled — no versions left
   └─RecipesBase [3cdcf5f2] log:
     ├─possible versions are: 0.4.0-1.2.1 or uninstalled
     ├─restricted by compatibility requirements with Plots [91a5bcdd] to versions: 0.4.0-1.2.1
     │ └─Plots [91a5bcdd] log:
     │   ├─possible versions are: 0.12.1-1.29.0 or uninstalled
     │   ├─restricted to versions * by an explicit requirement, leaving only versions 0.12.1-1.29.0
     │   ├─restricted by compatibility requirements with EntropyHub [3938faea] to versions: 1.10.3-1.29.0
     │   │ └─EntropyHub [3938faea] log: see above
     │   └─restricted by compatibility requirements with RecipesBase [3cdcf5f2] to versions: 1.0.0-1.23.6 or uninstalled, leaving only versions: 1.10.3-1.23.6
     │     └─RecipesBase [3cdcf5f2] log: see above
     ├─restricted by compatibility requirements with FourierAnalysis [e7e9c730] to versions: [0.7.0, 1.1.2]
     │ └─FourierAnalysis [e7e9c730] log: see above
     └─restricted by compatibility requirements with Plots [91a5bcdd] to versions: 1.0.0-1.2.1, leaving only versions: 1.1.2
       └─Plots [91a5bcdd] log: see above`

I tried installing it on Julia v 1.7 using Pkg.add("EntropyHub") and also ]add EntropyHub.

Best regards,
Yasir

**Comment by MattWillFlood** [comment]
Hi Yasir,
Could you post a screenshot of the error please?
To figure out why you are seeing this error, it helps if I can see the tree structure of dependencies.

Have you tried adding EntropyHub using the URL?
e.g.
] add "https://github.com/MattWillFlood/EntropyHub.jl"

Thanks :)

**Comment by duodenum96** [comment]
Hello Matt, thanks for the response.

Here is the screenshot for ]add "link"
![image](https://user-images.githubusercontent.com/70075569/171039310-86b3b099-d543-460e-956c-f370fbfb38b9.png)

And the screenshot for ]add EntropyHub
![image](https://user-images.githubusercontent.com/70075569/171039492-670837b6-2325-4aa3-a5c3-d3751b854554.png)

Thanks,
Yasir

**Comment by MattWillFlood** [comment]
Hi @duodenum96,
Just to  let you know, we are still working to fix this issue.
Thanks for your patience!
Matt

**Comment by MattWillFlood** [comment]
Hopefully this problem is fixed in the latest release (v1.0)!
Thanks for your patience!

(_The problem with compatabilities was due to a error in Dierckx.jl._
 _This package has been replaced by DataInterpolations.jl in the new release so this *shouldn't* happen again_)

If you experience any issues, please let me know :)
