### ISSUE TITLE
Extract entropy functions to a lighter-weight package

### ISSUE THREAD

**Issue by IanButterworth** [MattWillFlood/EntropyHub.jl#5]
There are a lot of deps here like `Plots.jl` that are more front-end than the core entropy calcs.

It would be helpful to make a `EntropyMetrics.jl` that this depends on, that the user could use without taking on plotting deps.

**Comment by Datseris** [comment]
This is done in a different package already, https://github.com/JuliaDynamics/ComplexityMeasures.jl

**Comment by MattWillFlood** [comment]
> There are a lot of deps here like `Plots.jl` that are more front-end than the core entropy calcs.
> 
> It would be helpful to make a `EntropyMetrics.jl` that this depends on, that the user could use without taking on plotting deps.

Thanks for the feedback @IanButterworth! I'll look into this for the next release (_but any guidance on how to do this would be welcomed_).
Plots.jl is infamously slow to load... hopefully that will improve as Julia grows.

**Comment by Datseris** [comment]
Use Julia package extensions. EDIT: Example for plotting in TimeseriesSurrogates.jl: https://github.com/JuliaDynamics/TimeseriesSurrogates.jl/blob/main/src/plotting/surrogate_plot.jl and https://github.com/JuliaDynamics/TimeseriesSurrogates.jl/blob/main/ext/TimeseriesSurrogatesVisualizations.jl and https://github.com/JuliaDynamics/TimeseriesSurrogates.jl/blob/main/Project.toml#L27

**Comment by MattWillFlood** [comment]
Thanks @Datseris !

**Comment by Datseris** [comment]
I've updated my comment above with links on how we do it for timeseries surrogates. Julia has made this very simple!

**Comment by MattWillFlood** [comment]
Much appreciated @Datseris , this is very helpful.
